"""empty message

Revision ID: 1afed77251e1
Revises: 
Create Date: 2022-04-29 05:30:14.636793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afed77251e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_products', sa.Column('Order', sa.Integer(), nullable=True))
    op.add_column('orders_products', sa.Column('Product', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products', 'product', ['Product'], ['product_id'])
    op.create_foreign_key(None, 'orders_products', 'order', ['Order'], ['order_id'])
    op.drop_column('orders_products', 'order')
    op.drop_column('orders_products', 'product')
    op.add_column('product_processes', sa.Column('Product', sa.Integer(), nullable=True))
    op.add_column('product_processes', sa.Column('Process', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'product_processes', type_='foreignkey')
    op.drop_constraint(None, 'product_processes', type_='foreignkey')
    op.create_foreign_key(None, 'product_processes', 'product', ['Product'], ['product_id'])
    op.create_foreign_key(None, 'product_processes', 'process', ['Process'], ['process_id'])
    op.drop_column('product_processes', 'process')
    op.drop_column('product_processes', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_processes', sa.Column('product', sa.INTEGER(), nullable=True))
    op.add_column('product_processes', sa.Column('process', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product_processes', type_='foreignkey')
    op.drop_constraint(None, 'product_processes', type_='foreignkey')
    op.create_foreign_key(None, 'product_processes', 'process', ['process'], ['process_id'])
    op.create_foreign_key(None, 'product_processes', 'product', ['product'], ['product_id'])
    op.drop_column('product_processes', 'Process')
    op.drop_column('product_processes', 'Product')
    op.add_column('orders_products', sa.Column('product', sa.INTEGER(), nullable=True))
    op.add_column('orders_products', sa.Column('order', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products', 'product', ['product'], ['product_id'])
    op.create_foreign_key(None, 'orders_products', 'order', ['order'], ['order_id'])
    op.drop_column('orders_products', 'Product')
    op.drop_column('orders_products', 'Order')
    # ### end Alembic commands ###
