"""empty message

Revision ID: 4fa4c8fdae16
Revises: 
Create Date: 2022-04-28 18:35:41.311846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa4c8fdae16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('product_processes')
    op.drop_table('orders_products')
    op.drop_table('process')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('process',
    sa.Column('process_id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(), nullable=True),
    sa.Column('Comment', sa.VARCHAR(), nullable=True),
    sa.Column('Completed', sa.BOOLEAN(), nullable=True),
    sa.Column('responsible_employee', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_employee'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.create_table('orders_products',
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('product', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.product_id'], )
    )
    op.create_table('product_processes',
    sa.Column('product', sa.INTEGER(), nullable=True),
    sa.Column('process', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['process'], ['process.process_id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.product_id'], )
    )
    op.create_table('order',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.VARCHAR(), nullable=True),
    sa.Column('Completed', sa.BOOLEAN(), nullable=True),
    sa.Column('Date to complete', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###
