"""empty message

Revision ID: 956359d8017e
Revises: 
Create Date: 2022-04-29 20:26:11.282421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956359d8017e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_in_order', type_='foreignkey')
    op.drop_column('process_in_order', 'process')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_in_order', sa.Column('process', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'process_in_order', 'process', ['process'], ['process_id'])
    # ### end Alembic commands ###
