"""empty message

Revision ID: ddc22c74b496
Revises: 4fa4c8fdae16
Create Date: 2022-04-28 18:37:43.121440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc22c74b496'
down_revision = '4fa4c8fdae16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('First name', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('Last name', sa.String(), nullable=True))
    op.drop_column('employee', 'Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('Name', sa.VARCHAR(), nullable=True))
    op.drop_column('employee', 'Last name')
    op.drop_column('employee', 'First name')
    # ### end Alembic commands ###
